CodeSystem: MedComMeasurementCodes
Id: medcom-measurement-codes
Title: "MedComMeasurementCodes"
Description: "CodeSystem "
* ^version  =  "1.0.0"
* ^status  =  #active
* ^date  =  "2025-03-26"
* ^caseSensitive = false
* ^experimental = false
// #{code} "{display string}" "{definition string}"
//* #MCS88019 "Blodtryk hjemme systolisk;Arm" "Arm—Blodtryk(systolisk) hjemme; tryk = ? mmHg" 
* #MCS88001 "Pt(motion)-Ugentligt; tid = ? time/uge" "Ugentligt;Pt(motion)"
* #MCS88002 "Pt(rygning)-Dagligt; antal = ?" "Dagligt;Pt(rygning)"
* #MCS88005 "Pt(rygning)-Rygestop tilbudt; arb.k.(0 1) = ?" "Rygestop tilbudt;Pt(rygning)"
* #MCS88006 "Pt(rygning)-ophørt = ? årstal" "Tobaksrygning ophørt;Pt(rygning)"
* #MCS88008 "Pt(rygning)-Udsættes du for passiv tobaksrygning; arb.k.(0 1) = ?" "Passiv tobaksrygning;Pt(rygning)"
* #MCS88009 "Pt(rygning)-Vil du gerne have hjælp til at holde op; arb.k.(0 1) = ?" "Rygestop hjælp ønskes;Pt(rygning)"
* #MCS88010 "Pt(rygning)-Vil du gerne holde op; arb.k.(0 1) = ?" "Vil du gerne holde op;Pt(rygning)"
* #MCS88011 "Pt(rygning)-Ryger du tobak; arb.akt.(dagligt; lejlighedsvis; ophørt; aldrig røget) = ?" "Ryger du tobak;Pt(rygning)"
* #MCS88014 "Pt(diabetes)-Antal diabeteskontroller aftalt i det kommende år; antal (værdi 0-10) = ?" "Diabeteskontrol aftalt;Pt(diabetes)"
* #MCS88015 "Lunge-Lungefunktionsundersøgelse FEV1; vol. = ? L" "FEV1;Lunge"
* #MCS88016 "Lunge-Lungefunktionsundersøgelse vitalkapasitet FVC; vol. = ? L" "FVC;Lunge"
* #MCS88017 "Lunge-FEV1/FVC; ratio = ?" "FEV1/FVC;Lunge"
* #MCS88019 "Arm-Blodtryk(systolisk) hjemme; tryk = ? mmHg" "Blodtryk hjemme systolisk;Arm"
* #MCS88019 ^property[0].code = #mmHg
* #MCS88020 "Arm-Blodtryk(diastolisk) hjemme; tryk = ? mmHg" "Blodtryk hjemme diastolisk;Arm"
* #MCS88021 "Pt(KOL) -MRC skala; arb.antal(værdi 1-5) = ?" "MRC skala;Pt(KOL)"
* #MCS88022 "Pt(KOL)-Antal eksacerbationer i det sidst forløbne år; antal (værdi 1-20) = ?" "Eksacerbationer;Pt(KOL)"
* #MCS88023 "Pt(KOL)-FEV1 i % af den forventede værdi (efter højde,alder og køn); ratio = ?" "FEV1 af forventet værdi;Pt(KOL)"
* #MCS88024 "Pt(rygning)-Antal pakkeår (20 cigaretter dagligt i et år) = ? år" "Pakkeår;Pt(rygning)"
* #MCS88025 "Hb(B)(mål)-HbA1c patientmål aftalt for kommende år; stofratio = ?" "HbA1c, patientaftalt mål;Hb(B)"
* #MCS88026 "P(mål)-LDL Kolesterol patientmål aftalt for kommende år; stofk. = ? mmol/L" "LDL-Kolesterol, patientaftalt mål;P"
* #MCS88027 "Arm(mål)-Blodtryk(systolisk) patientmål aftalt for kommende år = ? mmHg" "BT(sys), patientaftalt mål;Arm"
* #MCS88028 "Pt(mål)-Legeme; masse mål aftalt for kommende år = ? kg" "Legeme vægt, mål aftalt;Pt(mål)"
* #MCS88030 "Lunge-FEV1 reversibilitet = ? L" "FEV1 reversibilitet;Lunge"
* #MCS88032 "Pt(NYHA)-Hjerteinsufficiens funktionsklasse; antal (værdi 0-4) = ?" "Hjertesvigts funktionskl.;Pt(NYHA)"
* #MCS88033 "Arm(mål)-Blodtryk(diastolisk) patientmål aftalt for kommende år = ? mmHg" "BT(dia), patientaftalt mål;Arm"
* #MCS88034 "Pt(mål)-Legeme; massekoefficient(masse/kvadreret højde) mål aftalt for det kommende år  = ? kg/m�" "BMI, mål aftalt;Pt(mål)"
* #MCS88036 "Pt(alkohol)-Alkoholforbrug ugentlig; antal = ? Uge" "Alkoholforbrug;Pt(alkohol)"
* #MCS88039 "Pt-Står til rådighed for arbejdsmarkedet; arb.k.(0 1) = ?" "Til rådighed for arbejdsmark.;Pt"
* #MCS88040 "Pt(angst)-Angst scoreskema; antal (værdi 0-50) = ?" "ASS score;Pt(angst)"
* #MCS88041 "Pt(depression)-Major Depression Inventory; antal (værdi 0-50) = ?" "MDI score;Pt(depression)"
* #MCS88042 "Pt-Mini-Mental State Examination score; antal (værdi 0-30) = ?" "MMSE score;Pt"
* #MCS88043 "Pt(kost)-Er der talt om kost; arb.k.(0 1) = ?" "Er der talt om kost;Pt(kost)"
* #MCS88044 "Pt(øje)-øjenbaggrundsundersøgelse, fundusundersøgelse; arb.k.(0 1) = ?" "øjenus., fundusundersøgelse;Pt(øje)"
* #MCS88050 "Pt-Rejse sætte sig testen; antal (værdi 0-50) =  � 1/30s" "Rejse sætte sig testen;Pt"
* #MCS88052 "Pt(kost)-kostscore; antal (0-12) = ?" "Kostscore;Pt(kost)"
* #MCS88053 "Pt(selvvurderet helbred)-hvordan synes du dit helbred er alt i alt; arb.akt.(Fremragende, v�ldigt godt, godt, mindre godt, dårligt) = ?" "Helbred;Pt(selvvurderet helbred)"
* #MCS88058 "Pt(KOL) -GOLD Inddeling; arb.akt.(A; B; C; D; E) = ?" "GOLD Inddeling;Pt(KOL)"
* #MCS88059 "Pt(CMDQ) -Symptom; antal (værdi 0-48) = ?" "Symptom;Pt(CMDQ)"
* #MCS88060 "Pt(CMDQ) -Helbredsangst; antal (værdi 0-28)  = ?" "Helbredsangst;Pt(CMDQ)"
* #MCS88061 "Pt(CMDQ) -Angsttilstand; antal (værdi 0-16) = ?" "Angsttilstand;Pt(CMDQ)"
* #MCS88062 "Pt(CMDQ) -Depression; antal (værdi 0-24) = ?" "Depression;Pt(CMDQ)"
* #MCS88063 "Pt(CMDQ) -Alkohol; antal (værdi 0-4) = ?" "Alkohol;Pt(CMDQ)"
* #MCS88067 "Pt(diabetes)-Taljeomkreds mål aftalt for det kommende år; længde = ? M" "Taljeomkreds mål aftalt;Pt(diabet)"
* #MCS88068 "Pt(motion)-fysisk aktivitet i fritiden; arb.akt.(konkurrence; motionsidræt, lettere motion, stillesiddende) = ?" "Fysisk aktivitet fritid.;Pt(motion)"
* #MCS88069 "Pt(svangreundersøgelse)-Hvilken svangreundersøgelse;  arb.akt.(fårste; anden; tredje; fjerde) = ?" "Svangre us.;Pt(svangreundersøgelse)"
* #MCS88070 "Pt(bårneundersøgelse)-Hvilken bårneundersøgelse; arb.akt.( 1 uges; 5 ugers; 5 måneders; 1 års; 2 års; 3 års; 4 års; 5 års) = ?" "Bårne us.;Pt(bårneundersøgelse)"
* #MCS88071 "Pt(motion)-fysisk aktiv 30 minutter om dagen; arb.k.(0 1) = ?" "30 minutter om dagen;Pt(motion)"
* #MCS88072 "Pt(urinvejssymptomer)-Dansk Prostata Symptom Scoringsskema; arb.akt.(tømning; fyldning; andre; seksual) = ? " "DAN-PSS;Pt(urinvejssymptomer)"
* #MCS88099 "Lunge-FEV1/FEV6 ratio = ?" "FEV1/FEV6;Lunge"
* #MCS88100 "Lunge-Lungefunktionsundersøgelse COPD FEV6; vol. = ? L" "FEV6;Lunge"
* #MCS88101 "Halspodning A streptokok antigen;Strep A test"
* #MCS88102 "Pt-Peakflow" "Peakflow;Pt"
* #MCS88104 "Lunge-FVC reversibilitet = ? L" "FVC reversibilitet;Lunge"
* #MCS88105 "Lunge-FEV1/FVC reversibilitet; ratio = ?" "FEV1/FVC reversibilitet;Lunge"
* #MCS88106 "Pt(problematisk stofbrug)-Hash 4 eller flere dg inden for den seneste mnd og/eller andre euforiserende stoffer, som fx amfetamin, kokain og ecstasy 1 eller flere dg inden for den seneste mnd; arb.k.(0 1) = ?" "Stoffer;Pt(problematisk stofbrug)"
* #MCS88108 "Pt(stress)-Stress scoreskema; antal (værdi 0-20) = ?" "Stress score;Pt(stress)"
* #MCS88109 "Lunge-FVC/FVC forventet;  ratio= ?" "FVC/FVC forventet;Lunge"
* #MCS88110 "Lunge-FEV1/FEV1 forventet; ratio = ?" "FEV1/FEV1 forventet;Lunge"
* #MCS88111 "Lunge-Set Score FVC lungefunktion = ?" "Set Score FVC;Lunge"
* #MCS88112 "Lunge-Set Score FEV1 lungefunktion = ?" "Set score FEV1;Lunge"
* #MCS88113 "Pt(urinvejssymptomer)-Væske+vandladningsskema; arb.akt.(normal; unormal) = ?" "Væske+vandskema;Pt(urinvejssympt)"
* #MCS88114 "Pt(voksen)-Hovedpinedagbog Diagnostik; arb.akt.(normal; unormal) = ?" "Hovedpinedagbog;Pt(voksen)"
* #MCS88115 "Pt(barn)-Væske+vandladningsskema; arb.akt.(normal; unormal) = ?" "Væske+vandskema;Pt(barn)"
* #MCS88116 "Pt(diabetes)-Debutår = ? årstal" "Debutår;Pt(diabetes)"
* #MCS88117 "Pt(diabetes)-Retinopati; arb.k.(0 1) = ?" "Retinopati;Pt(diabetes)"
* #MCS88118 "Pt-Positive Expiratory Pressure" "PEP-fløjte;Pt"
* #MCS88119 "Tungeskrab;Tungeskrab"
* #MCS88120 "Pt(CCS)-Stabil Angina Pectoris; antal (værdi 1-4) = ?" "Stabil Angina Pectoris;Pt(CCS)"
* #MCS88121 "Pt-Residualurin; mængde = ? L" "Residualurin;Pt"
* #MCS88122 "Pt-Respiration; frekvens = ? X 1/min" "Respirationsfrekvens;Pt"
* #MCS88123 "Pt-Væske pr os, seneste døgn; mængde = ? L" "Væske pr os, 24h;Pt"
* #MCS88124 "Pt-Barthel-20 Index; antal (værdi 0-20) = ?" "Barthel-20 Index;Pt"
* #MCS88125 "Pt-Tidlig Opsporing af Begyndende Sygdom (TOBS) score; antal (værdi 0-15) = ?" "TOBS score;Pt"
* #MCS88126 "Pt-Bevidsthedsniveau; arb.antal(værdi 0-3) = ?" "Bevidsthed;Pt"
* #MCS88127 "Pt(hjælp afhængighed)-Spisning; antal(værdi 0-2) = ?" "Spisning;Pt(hjælp afhængighed)"
* #MCS88128 "Pt(hjælp afhængighed)-Forflytning fra seng til stol; antal(værdi 0-3) = ?" "Forflytning;Pt(hjælp afhængighed)"
* #MCS88129 "Pt(hjælp afhængighed)-Personlig hygiejne; antal(værdi 0-1) = ?" "Pers.hygiejne;Pt(hjælp afhængighed)"
* #MCS88130 "Pt(hjælp afhængighed)-Toiletbesøg; antal(værdi 0-2) = ?" "Toiletbesøg;Pt(hjælp afhængighed)"
* #MCS88131 "Pt(hjælp afhængighed)-Badning; antal(værdi 0-1) = ?" "Badning;Pt(hjælp afhængighed)"
* #MCS88132 "Pt(hjælp afhængighed)-Mobilitet indendårs; antal(værdi 0-3) = ?" "Mobilitet;Pt(hjælp afhængighed)"
* #MCS88133 "Pt(hjælp afhængighed)-Trappegang; antal(værdi 0-2) = ?" "Trappegang;Pt(hjælp afhængighed)"
* #MCS88134 "Pt(hjælp afhængighed)-Påklædning; antal(værdi 0-2) = ?" "Påklædning;Pt(hjælp afhængighed)"
* #MCS88135 "Pt(hjælp afhængighed)-Tarmkontrol seneste uge; antal(værdi 0-2) = ?" "Tarmkontrol;Pt(hjælp afhængighed)"
* #MCS88136 "Pt(hjælp afhængighed)-Blårekontrol seneste uge; antal(værdi 0-2) = ?" "Blårekontrol;Pt(hjælp afhængighed)"
* #MCS88137 "Pt-COPD Assessment Test (CAT) score; antal(værdi 0-40) = ?" "CAT score;Pt"
* #MCS88138 "Pt-Common Mental Disorders Questionnaire (CMDQ) score; egenskabsart(liste; proc.)" "CMDQ score gruppe;Pt"
* #MCS88139 "Pt-Estimeret Lungealder; tid = ? år" "Estimeret lungealder;Pt"
* #MCS88140 "Pt(kost)-Anser du din kost for at våre sund - jf. Fødevarestyrelsens kostråd; arb.k.(0 1) = ?" "Sund kost;Pt(kost)"
* #MCS88141 "Pt-Kost,Rygning,Alkohol,Motion(KRAM); arb.akt.(sund;usund) = ?" "KRAM;Pt"
* #MCS88142 "Pt-Inhalationsteknik for indtagelse af inhalationsmedicin kontrolleret i praksis; antal(værdi 0-1) = ?" "Inhalationsteknik kontrol;Pt"
* #MCS88143 "Pt-Lungefunktion undersøgt; arb.akt.(Ja; Nej; Ej relevant; Ej muligt) = ?" "Lungefunktion undersøgt;Pt"
* #MCS88144 "Pt-Henvist til Rehabilitering; arb.akt.(Ja; Nej; Ikke egnet; Ønsker ikke; Ej relevant; Ej spurgt) = ?" "Henvist til Rehabilitering;Pt"
* #MCS88145 "Pt-Fysisk anstrengende træning/motion; arb.akt.(Dagligt; Ugentligt; månedligt; Ingen; Undgår; Ej spurgt) = ?" "Fysisk træning/motion;Pt"
* #MCS88146 "Pt-Heartscore(køn,alder,systolisk blodtryk,cholesterol); ratio=?" "Heartscore;Pt"
* #MCS88147 "Pt-Manniche VAS-score(total); antal(værdi 0-60) = ?" "Manniche VAS-score(total);Pt"
* #MCS88148 "Pt-Subgroups for Targeted Treatment (STarT) score; arb.akt.(Lav; Middel; Høj) = ?" "STarT score;Pt"
* #MCS88149 "Pt(mål)-Motion, mål aftalt for kommende år; arb.akt.(Dagligt; Ugentligt; månedligt; Ingen; Undgår; Ej spurgt) = ?" "Motion, mål aftalt;Pt(mål)"
* #MCS88150 "Pt(mål)-Alkoholforbrug, mål aftalt for kommende år; antal = ? genstand/uge" "Alkohol, mål aftalt;Pt(mål)"
* #MCS88151 "Pt(mål)-Rygning, mål aftalt for kommende år; arb.akt.(dagligt; lejlighedsvis; ophørt; aldrig røget) = ?" "Rygning, mål aftalt;Pt(mål)"
* #MCS88152 "Pt(diabetes)-øjenlægekontrol; arb.akt.(ja;nej;ej relevant) = ?" "øjenlægekontrol;Pt(diatetes)"
* #MCS88153 "Pt(diabetes)-Fodundersøgelse; arb.akt.(ja;nej;ej relevant) = ?" "Fodundersøgelse;Pt(diabetes)"
* #MCS88154 "Hjerte-Ejection Fraction (EF), uddrivningsfunktion fra hjerte, ratio = ? (værdi 0-100)" "Ejection Fraction (EF); Hjerte"
* #MCS88155 "Pt(rygning)-E-cigaret status; arb.akt.(bruger, tidligere bruger, aldrig bruger)" "E-cigaret status;Pt(rygning)"
* #MCS88156 "Pt-Arbejdsbelastning; effekt = ? W" "Arbejdsbelastning;Pt"
* #MCS88157 "Pt-Maximalt iltoptag; vol.hast.(proc.) = ? L/min" "Maximalt iltoptag;Pt"
* #MCS88158 "Pt-Kondital; vol.hast.(proc.) = ? mL/kg/min" "Kondital;Pt"
* #MCS88159 "Pt-Iltbehandling i hjemmet; arb.k.(0 1) = ?" "Iltbehandling i hjemmet;Pt"
* #MCS88160 "Pt(psoriasis)-Livskvalitetsindex (DLQI); antal(værdi 0-30) = ?" "Livskvalitetsindex;Pt(psoriasis)"
* #MCS88161 "Pt(psoriasis)-Symptomscore (PSSD); antal(værdi 0-100) = ?" "Symptomscore;Pt(psoriasis)"
* #MCS88162 "Pt(psoriasis)-Sygdomstegnscore (PSSD); antal(værdi 0-100) = ?" "Sygdomsscore;Pt(psoriasis)"
* #MCS88163 "Pt(psoriasis)-Hudpåvirkning (BSA); antal(værdi 0-100) = ?" "Hudpåvirkning;Pt(psoriasis)"
* #MCS88164 "Pt(psoriasis)-Hudpåvirkning intimområde (BSA);  arb.k.(0 1) = ?" "Hudpåvirkning intim;Pt(psoriasis)"
* #MCS88165 "Pt(psoriasis)-Screening for psoriasisgigt (PEST); antal(værdi 0-5) = ?" "Psoriasisgigtscore;Pt(psoriasis)"
* #MCS88166 "Pt(psoriasis)-Hjerte/kar helbredsmonitorering;  arb.k.(0 1) = ?" "Hjerte/kar-helbred;Pt(psoriasis)"
* #MCS88167 "Pt(psoriasis)-Bivirkninger til behandling; arb.k.(0 1) = ?" "Bivirkninger;Pt(psoriasis)"
* #MCS88168 "Pt(psoriasis)-Samlet helbredspåvirkning i seneste uge (PGA); antal(værdi 0-10) = ?" "Helbredspåvirkning;Pt(psoriasis)"
* #MCS88169 "Pt(psoriasis)-Generel trivsel i seneste 2 uger (MDI); antal(værdi 0-5) = ?" "Generel trivsel;Pt(psoriasis)"
* #MCS88170 "Pt(psoriasis)-Behov for stillingtagning til reumatolog; arb.k.(0 1) = ?" "Behov-reumatolog;Pt(psoriasis)"
* #MCS88171 "Pt(AFLI)-Tid i Terapeutisk Index over 12 mdr. (TTI); ratio = ?" "TTI (12mdr);Pt(AFLI)"
* #MCS88172 "Pt-Problem Areas in Diabetes (PAID-5); antal(værdi 0-20) = ?" "PAID-5;Pt"
* #MCS88173 "Pt-Trivselsindekset (WHO-5); antal(værdi 0-100) = ? " "WHO-5;Pt"
* #MCS88174 "Pt(rygning)-Ryger du; arb.akt.(ja;nej) = ?" "Ryger du;Pt"
* #MCS88175 "Pt(diabetes)-Øjne undersøgt for diabetesforandringer indenfor de seneste 2 år; arb.akt.(ja;nej;ej besvaret) = ?" "Øjne undersøgt ifm. diabetes;Pt"
* #MCS88176 "Pt(diabetes)-Fødder undersøgt hos fodterapeut indenfor det seneste år; arb.akt.(ja;nej;ej besvaret) = ?" "Fødder undersøgt hos fodterapeut;Pt"
* #MCS88177 "Pt(psoriasis)-Hudpåvirkning Hoved; arb.k.(0 1) = ?" "Hudpåvirkning Hoved;Pt(psoriasis)"
* #MCS88178 "Pt(psoriasis)-Hudpåvirkning Overkrop; arb.k.(0 1) = ?" "Hudpåvirkn. Overkrop;Pt(psoriasis)"
* #MCS88179 "Pt(psoriasis)-Hudpåvirkning Arme; arb.k.(0 1) = ?" "Hudpåvirkning Arme;Pt(psoriasis)"
* #MCS88180 "Pt(psoriasis)-Hudpåvirkning Ben; arb.k.(0 1) = ?" "Hudpåvirkning Ben;Pt(psoriasis)"
* #MCS88181 "Pt(psoriasis)-Emner til samtale; arb.k.(0 1) = ?" "Samtale;Pt(psoriasis)"
* #MCS88182 "Pt(psoriasis)-Hudpåvirkning Ingen; arb.k.(0 1) = ?" "Hudpåvirkning Ingen;Pt(psoriasis)"
* #MCS88183 "Pt-SCORE2 Hjerte (køn,alder,systolisk blodtryk,LDL-kolesterol,rygestatus); ratio=?" "SCORE2 Hjerte;Pt"
* #MCS88184 "Lunge-FEV1 i % af forventede værdi ( ift. højde, alder og køn) - efter reversibilitet; ratio = ?" "FEV1% - efter reversibilitet;Lunge"
* #MCS88185 "P(FLP mål)-LDL kolesterol beregnet anbefalet mål for kommende år; stofk. = ? mmol/L" "LDL-Kolesterol, beregn.anbef.mål;P"
* #MCS88186 "Hb(B)(FLP mål)-HbA1c beregnet anbefalet mål for kommende år; stofratio = ?" "HbA1c, beregnet anbefalet mål;Hb(B)"
* #MCS88187 "Arm(FLP mål)-Blodtryk(systolisk) beregnet anbefalet mål for kommende år = ? mmHg" "BT(sys), beregnet anbefalet mål;Arm"
* #MCS88188 "Arm(FLP mål)-Blodtryk(diastolisk) beregnet anbefalet mål for kommende år = ? mmHg" "BT(dia), beregnet anbefalet mål;Arm"
* #MCS88189 "Pt(AFLI)-Tid i Terapeutisk Index over 3 mdr. (TTI); ratio = ?" "TTI (3mdr);Pt(AFLI)"
* #MCS88190 "Pt(AFLI)-Tid i Terapeutisk Index over 6 mdr. (TTI); ratio = ?" "TTI (6mdr);Pt(AFLI)"
* #MCS88191 "Pt(AFLI)-Tid i Terapeutisk Index total interval (TTI); ratio = ?" "TTI (total interval);Pt(AFLI)"
* #MCS88192 "Pt-Skridt; antal per dag (værdi) = ?" "Skridt per dag;Pt"
* #MCS88193 "Pt-Skridt; antal per uge (værdi) = ?" "Skridt per uge;Pt"
* #MCS88194 "Pt-Skridt; antal (værdi) = ?" "Skridt;Pt"
* #MCS88195 "Pt-Generelt fysisk helbreds score (PROMIS-10); antal(værdi 16.2-67.7) = ?" "PROMIS-10 Fysisk helbred;Pt"
* #MCS88196 "Pt-Generelt mentalt helbreds score (PROMIS-10); antal(værdi 21.2-67.6) = ?" "PROMIS-10 Mentalt helbred;Pt"
* #MCS88197 "Pt-SCORE2 Diabetes (køn,alder,debutår,systolisk blodtryk,total- og HDL-kolesterol,rygestatus,eGFR,HbA1c); ratio=?" "SCORE2 Diabetes;Pt"
* #MCS88198 "Pt-BASIC (Brief Assessment of Impaired Cognition SCORE, Demens); antal(værdi 0-25) = ?" "BASIC SCORE (demens);Pt"
* #MCS90001 "øjenscreenings-indikation (0-5);øjenscreenings-indikation"
* #MCS90002 "Tidligere kataraktoperation;højre øje" "Tidligere kataraktop.;højre øje"
* #MCS90003 "Tidligere kataraktoperation; venstre øje" "Tidligere kataraktop.; venstre øje"
* #MCS90004 "Tidligere vitreoretinal kirurgi for diabeteskomplikation;højre øje" "Tidl vitreoretinal kirg;højre øje"
* #MCS90005 "Tidligere vitreoretinal kirurgi for diabeteskomplikation;venstre øje" "Tidl vitreoretinal kirg;venstre øje"
* #MCS90006 "Synsstyrke;højre øje" "Synsstyrke;højre øje"
* #MCS90007 "Synsstyrke;venstre øje" "Synsstyrke;venstre øje"
* #MCS90010 "Retinastatus;højre øje ((0-7)(51-55))" "Retinastatus;højre øje"
* #MCS90011 "Retinastatus;venstre øje ((0-7)(51-55))" "Retinastatus;venstre øje"
* #MCS90012 "Maculopati-status;højre øje (0-7)" "Maculopati-status;højre øje"
* #MCS90013 "Maculopati-status;venstre øje (0-7)" "Maculopati-status;venstre øje"
* #MCS90014 "Indikation for næste øjenlægekontakt (0-6);Indikation f næste øjenlægekontakt"
* #MCS90015 "Tidspunkt for næste Screening ;Tidspunkt for næste Screening"
* #MCS90016 "Slårede medier-Katarakt;højre øje" "Slårede medier-Katarakt;højre øje"
* #MCS90017 "Slårede medier-Katarakt;venstre øje" "Slårede medier-Katarakt;venstre øje"
* #MCS90018 "Slårede medier-Glaslegemeblødning;højre øje" "Slår med.-Glaslegemebl;højre øje"
* #MCS90019 "Slårede medier-Glaslegemeblødning;venstre øje" "Slår med.-Glaslegemebl;venstre øje"
* #MCS90020 "Slårede medier-Anden / ukendt årsag;højre øje" "Slår med.-An/ukendt årsag;h� øje"
* #MCS90021 "Slårede medier-Anden / ukendt årsag;venstre øje" "Slår med.-An/ukendt årsag;ven øje"
