CodeSystem: MedComMeasurementCodes
Id: medcom-measurement-codes
Title: "MedComMeasurementCodes"
Description: "CodeSystem "
* ^version  =  "1.0.0"
* ^status  =  #active
* ^date  =  "2025-03-26"
* ^caseSensitive = false
* ^experimental = false
// #{code} "{display string}" "{definition string}"
//* #MCS88019 "Blodtryk hjemme systolisk;Arm" "Arm—Blodtryk(systolisk) hjemme; tryk = ? mmHg" 
* #MCS88001	"Ugentligt;Pt(motion)"	"Pt(motion)-Ugentligt; tid = ? time/uge"	
* #MCS88002	"Dagligt;Pt(rygning)"	"Pt(rygning)-Dagligt; antal = ?"	
* #MCS88005	"Rygestop tilbudt;Pt(rygning)"	"Pt(rygning)-Rygestop tilbudt; arb.k.(0 1) = ?"	
* #MCS88006	"Tobaksrygning ophørt;Pt(rygning)"	"Pt(rygning)-ophørt = ? årstal"	
* #MCS88008	"Passiv tobaksrygning;Pt(rygning)"	"Pt(rygning)-Udsættes du for passiv tobaksrygning; arb.k.(0 1) = ?"	
* #MCS88009	"Rygestop hjælp ønskes;Pt(rygning)"	"Pt(rygning)-Vil du gerne have hjælp til at holde op; arb.k.(0 1) = ?"	
* #MCS88010	"Vil du gerne holde op;Pt(rygning)"	"Pt(rygning)-Vil du gerne holde op; arb.k.(0 1) = ?"	
* #MCS88011	"Ryger du tobak;Pt(rygning)"	"Pt(rygning)-Ryger du tobak; arb.akt.(dagligt; lejlighedsvis; ophørt; aldrig røget) = ?"	
* #MCS88014	"Diabeteskontrol aftalt;Pt(diabetes)"	"Pt(diabetes)-Antal diabeteskontroller aftalt i det kommende år; antal (værdi 0-10) = ?"	
* #MCS88015	"FEV1;Lunge"	"Lunge-Lungefunktionsundersøgelse FEV1; vol. = ? L"	
* #MCS88016	"FVC;Lunge"	"Lunge-Lungefunktionsundersøgelse vitalkapasitet FVC; vol. = ? L"	
* #MCS88017	"FEV1/FVC;Lunge"	"Lunge-FEV1/FVC; ratio = ?"	
* #MCS88019	"Blodtryk hjemme systolisk;Arm"	"Arm-Blodtryk(systolisk) hjemme; tryk = ? mmHg"	
* #MCS88020	"Blodtryk hjemme diastolisk;Arm"	"Arm-Blodtryk(diastolisk) hjemme; tryk = ? mmHg"	
* #MCS88021	"MRC skala;Pt(KOL)"	"Pt(KOL) -MRC skala; arb.antal(værdi 1-5) = ?"	
* #MCS88022	"Eksacerbationer;Pt(KOL)"	"Pt(KOL)-Antal eksacerbationer i det sidst forløbne år; antal (værdi 1-20) = ?"	
* #MCS88023	"FEV1 af forventet værdi;Pt(KOL)"	"Pt(KOL)-FEV1 i % af den forventede værdi (efter højde,alder og køn); ratio = ?"	
* #MCS88024	"Pakkeår;Pt(rygning)"	"Pt(rygning)-Antal pakkeår (20 cigaretter dagligt i et år) = ? år"	
* #MCS88025	"HbA1c, patientaftalt mål;Hb(B)"	"Hb(B)(mål)-HbA1c patientmål aftalt for kommende år; stofratio = ?"	
* #MCS88026	"LDL-Kolesterol, patientaftalt mål;P"	"P(mål)-LDL Kolesterol patientmål aftalt for kommende år; stofk. = ? mmol/L"	
* #MCS88027	"BT(sys), patientaftalt mål;Arm"	"Arm(mål)-Blodtryk(systolisk) patientmål aftalt for kommende år = ? mmHg"	
* #MCS88028	"Legeme vægt, mål aftalt;Pt(mål)"	"Pt(mål)-Legeme; masse mål aftalt for kommende år = ? kg"	
* #MCS88030	"FEV1 reversibilitet;Lunge"	"Lunge-FEV1 reversibilitet = ? L"	
* #MCS88032	"Hjertesvigts funktionskl.;Pt(NYHA)"	"Pt(NYHA)-Hjerteinsufficiens funktionsklasse; antal (værdi 0-4) = ?"	
* #MCS88033	"BT(dia), patientaftalt mål;Arm"	"Arm(mål)-Blodtryk(diastolisk) patientmål aftalt for kommende år = ? mmHg"	
* #MCS88034	"BMI, mål aftalt;Pt(mål)"	"Pt(mål)-Legeme; massekoefficient(masse/kvadreret højde) mål aftalt for det kommende år  = ? kg/m�"	
* #MCS88036	"Alkoholforbrug;Pt(alkohol)"	"Pt(alkohol)-Alkoholforbrug ugentlig; antal = ? Uge"	
* #MCS88039	"Til rådighed for arbejdsmark.;Pt"	"Pt-Står til rådighed for arbejdsmarkedet; arb.k.(0 1) = ?"	
* #MCS88040	"ASS score;Pt(angst)"	"Pt(angst)-Angst scoreskema; antal (værdi 0-50) = ?"	
* #MCS88041	"MDI score;Pt(depression)"	"Pt(depression)-Major Depression Inventory; antal (værdi 0-50) = ?"	
* #MCS88042	"MMSE score;Pt"	"Pt-Mini-Mental State Examination score; antal (værdi 0-30) = ?"	
* #MCS88043	"Er der talt om kost;Pt(kost)"	"Pt(kost)-Er der talt om kost; arb.k.(0 1) = ?"	
* #MCS88044	"øjenus., fundusundersøgelse;Pt(øje)"	"Pt(øje)-øjenbaggrundsundersøgelse, fundusundersøgelse; arb.k.(0 1) = ?"	
* #MCS88050	"Rejse sætte sig testen;Pt"	"Pt-Rejse sætte sig testen; antal (værdi 0-50) =  � 1/30s"	
* #MCS88052	"Kostscore;Pt(kost)"	"Pt(kost)-kostscore; antal (0-12) = ?"	
* #MCS88053	"Helbred;Pt(selvvurderet helbred)"	"Pt(selvvurderet helbred)-hvordan synes du dit helbred er alt i alt; arb.akt.(Fremragende, v�ldigt godt, godt, mindre godt, dårligt) = ?"	
* #MCS88058	"GOLD Inddeling;Pt(KOL)"	"Pt(KOL) -GOLD Inddeling; arb.akt.(A; B; C; D; E) = ?"	
* #MCS88059	"Symptom;Pt(CMDQ)"	"Pt(CMDQ) -Symptom; antal (værdi 0-48) = ?"	
* #MCS88060	"Helbredsangst;Pt(CMDQ)"	"Pt(CMDQ) -Helbredsangst; antal (værdi 0-28)  = ?"	
* #MCS88061	"Angsttilstand;Pt(CMDQ)"	"Pt(CMDQ) -Angsttilstand; antal (værdi 0-16) = ?"	
* #MCS88062	"Depression;Pt(CMDQ)"	"Pt(CMDQ) -Depression; antal (værdi 0-24) = ?"	
* #MCS88063	"Alkohol;Pt(CMDQ)"	"Pt(CMDQ) -Alkohol; antal (værdi 0-4) = ?"	
* #MCS88067	"Taljeomkreds mål aftalt;Pt(diabet)"	"Pt(diabetes)-Taljeomkreds mål aftalt for det kommende år; længde = ? M"	
* #MCS88068	"Fysisk aktivitet fritid.;Pt(motion)"	"Pt(motion)-fysisk aktivitet i fritiden; arb.akt.(konkurrence; motionsidræt, lettere motion, stillesiddende) = ?"	
* #MCS88069	"Svangre us.;Pt(svangreundersøgelse)"	"Pt(svangreundersøgelse)-Hvilken svangreundersøgelse;  arb.akt.(fårste; anden; tredje; fjerde) = ?"	
* #MCS88070	"Bårne us.;Pt(bårneundersøgelse)"	"Pt(bårneundersøgelse)-Hvilken bårneundersøgelse; arb.akt.( 1 uges; 5 ugers; 5 måneders; 1 års; 2 års; 3 års; 4 års; 5 års) = ?"	
* #MCS88071	"30 minutter om dagen;Pt(motion)"	"Pt(motion)-fysisk aktiv 30 minutter om dagen; arb.k.(0 1) = ?"	
* #MCS88072	"DAN-PSS;Pt(urinvejssymptomer)"	"Pt(urinvejssymptomer)-Dansk Prostata Symptom Scoringsskema; arb.akt.(tømning; fyldning; andre; seksual) = ? "	
* #MCS88099	"FEV1/FEV6;Lunge"	"Lunge-FEV1/FEV6 ratio = ?"	
* #MCS88100	"FEV6;Lunge"	"Lunge-Lungefunktionsundersøgelse COPD FEV6; vol. = ? L"	
* #MCS88101	""	"Halspodning A streptokok antigen;Strep A test"	
* #MCS88102	"Peakflow;Pt"	"Pt-Peakflow"	
* #MCS88104	"FVC reversibilitet;Lunge"	"Lunge-FVC reversibilitet = ? L"	
* #MCS88105	"FEV1/FVC reversibilitet;Lunge"	"Lunge-FEV1/FVC reversibilitet; ratio = ?"	
* #MCS88106	"Stoffer;Pt(problematisk stofbrug)"	"Pt(problematisk stofbrug)-Hash 4 eller flere dg inden for den seneste mnd og/eller andre euforiserende stoffer, som fx amfetamin, kokain og ecstasy 1 eller flere dg inden for den seneste mnd; arb.k.(0 1) = ?"	
* #MCS88108	"Stress score;Pt(stress)"	"Pt(stress)-Stress scoreskema; antal (værdi 0-20) = ?"	
* #MCS88109	"FVC/FVC forventet;Lunge"	"Lunge-FVC/FVC forventet;  ratio= ?"	
* #MCS88110	"FEV1/FEV1 forventet;Lunge"	"Lunge-FEV1/FEV1 forventet; ratio = ?"	
* #MCS88111	"Set Score FVC;Lunge"	"Lunge-Set Score FVC lungefunktion = ?"	
* #MCS88112	"Set score FEV1;Lunge"	"Lunge-Set Score FEV1 lungefunktion = ?"	
* #MCS88113	"Væske+vandskema;Pt(urinvejssympt)"	"Pt(urinvejssymptomer)-Væske+vandladningsskema; arb.akt.(normal; unormal) = ?"	
* #MCS88114	"Hovedpinedagbog;Pt(voksen)"	"Pt(voksen)-Hovedpinedagbog Diagnostik; arb.akt.(normal; unormal) = ?"	
* #MCS88115	"Væske+vandskema;Pt(barn)"	"Pt(barn)-Væske+vandladningsskema; arb.akt.(normal; unormal) = ?"	
* #MCS88116	"Debutår;Pt(diabetes)"	"Pt(diabetes)-Debutår = ? årstal"	
* #MCS88117	"Retinopati;Pt(diabetes)"	"Pt(diabetes)-Retinopati; arb.k.(0 1) = ?"	
* #MCS88118	"PEP-fløjte;Pt"	"Pt-Positive Expiratory Pressure"	
* #MCS88119	""	"Tungeskrab;Tungeskrab"	
* #MCS88120	"Stabil Angina Pectoris;Pt(CCS)"	"Pt(CCS)-Stabil Angina Pectoris; antal (værdi 1-4) = ?"	
* #MCS88121	"Residualurin;Pt"	"Pt-Residualurin; mængde = ? L"	
* #MCS88122	"Respirationsfrekvens;Pt"	"Pt-Respiration; frekvens = ? X 1/min"	
* #MCS88123	"Væske pr os, 24h;Pt"	"Pt-Væske pr os, seneste døgn; mængde = ? L"	
* #MCS88124	"Barthel-20 Index;Pt"	"Pt-Barthel-20 Index; antal (værdi 0-20) = ?"	
* #MCS88125	"TOBS score;Pt"	"Pt-Tidlig Opsporing af Begyndende Sygdom (TOBS) score; antal (værdi 0-15) = ?"	
* #MCS88126	"Bevidsthed;Pt"	"Pt-Bevidsthedsniveau; arb.antal(værdi 0-3) = ?"	
* #MCS88127	"Spisning;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Spisning; antal(værdi 0-2) = ?"	
* #MCS88128	"Forflytning;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Forflytning fra seng til stol; antal(værdi 0-3) = ?"	
* #MCS88129	"Pers.hygiejne;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Personlig hygiejne; antal(værdi 0-1) = ?"	
* #MCS88130	"Toiletbesøg;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Toiletbesøg; antal(værdi 0-2) = ?"	
* #MCS88131	"Badning;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Badning; antal(værdi 0-1) = ?"	
* #MCS88132	"Mobilitet;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Mobilitet indendårs; antal(værdi 0-3) = ?"	
* #MCS88133	"Trappegang;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Trappegang; antal(værdi 0-2) = ?"	
* #MCS88134	"Påklædning;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Påklædning; antal(værdi 0-2) = ?"	
* #MCS88135	"Tarmkontrol;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Tarmkontrol seneste uge; antal(værdi 0-2) = ?"	
* #MCS88136	"Blårekontrol;Pt(hjælp afhængighed)"	"Pt(hjælp afhængighed)-Blårekontrol seneste uge; antal(værdi 0-2) = ?"	
* #MCS88137	"CAT score;Pt"	"Pt-COPD Assessment Test (CAT) score; antal(værdi 0-40) = ?"	
* #MCS88138	"CMDQ score gruppe;Pt"	"Pt-Common Mental Disorders Questionnaire (CMDQ) score; egenskabsart(liste; proc.)"	
* #MCS88139	"Estimeret lungealder;Pt"	"Pt-Estimeret Lungealder; tid = ? år"	
* #MCS88140	"Sund kost;Pt(kost)"	"Pt(kost)-Anser du din kost for at våre sund - jf. Fødevarestyrelsens kostråd; arb.k.(0 1) = ?"	
* #MCS88141	"KRAM;Pt"	"Pt-Kost,Rygning,Alkohol,Motion(KRAM); arb.akt.(sund;usund) = ?"	
* #MCS88142	"Inhalationsteknik kontrol;Pt"	"Pt-Inhalationsteknik for indtagelse af inhalationsmedicin kontrolleret i praksis; antal(værdi 0-1) = ?"	
* #MCS88143	"Lungefunktion undersøgt;Pt"	"Pt-Lungefunktion undersøgt; arb.akt.(Ja; Nej; Ej relevant; Ej muligt) = ?"	
* #MCS88144	"Henvist til Rehabilitering;Pt"	"Pt-Henvist til Rehabilitering; arb.akt.(Ja; Nej; Ikke egnet; Ønsker ikke; Ej relevant; Ej spurgt) = ?"	
* #MCS88145	"Fysisk træning/motion;Pt"	"Pt-Fysisk anstrengende træning/motion; arb.akt.(Dagligt; Ugentligt; månedligt; Ingen; Undgår; Ej spurgt) = ?"	
* #MCS88146	"Heartscore;Pt"	"Pt-Heartscore(køn,alder,systolisk blodtryk,cholesterol); ratio=?"	
* #MCS88147	"Manniche VAS-score(total);Pt"	"Pt-Manniche VAS-score(total); antal(værdi 0-60) = ?"	
* #MCS88148	"STarT score;Pt"	"Pt-Subgroups for Targeted Treatment (STarT) score; arb.akt.(Lav; Middel; Høj) = ?"	
* #MCS88149	"Motion, mål aftalt;Pt(mål)"	"Pt(mål)-Motion, mål aftalt for kommende år; arb.akt.(Dagligt; Ugentligt; månedligt; Ingen; Undgår; Ej spurgt) = ?"	
* #MCS88150	"Alkohol, mål aftalt;Pt(mål)"	"Pt(mål)-Alkoholforbrug, mål aftalt for kommende år; antal = ? genstand/uge"	
* #MCS88151	"Rygning, mål aftalt;Pt(mål)"	"Pt(mål)-Rygning, mål aftalt for kommende år; arb.akt.(dagligt; lejlighedsvis; ophørt; aldrig røget) = ?"	
* #MCS88152	"øjenlægekontrol;Pt(diatetes)"	"Pt(diabetes)-øjenlægekontrol; arb.akt.(ja;nej;ej relevant) = ?"	
* #MCS88153	"Fodundersøgelse;Pt(diabetes)"	"Pt(diabetes)-Fodundersøgelse; arb.akt.(ja;nej;ej relevant) = ?"	
* #MCS88154	"Ejection Fraction (EF); Hjerte"	"Hjerte-Ejection Fraction (EF), uddrivningsfunktion fra hjerte, ratio = ? (værdi 0-100)"	
* #MCS88155	"E-cigaret status;Pt(rygning)"	"Pt(rygning)-E-cigaret status; arb.akt.(bruger, tidligere bruger, aldrig bruger)"	
* #MCS88156	"Arbejdsbelastning;Pt"	"Pt-Arbejdsbelastning; effekt = ? W"	
* #MCS88157	"Maximalt iltoptag;Pt"	"Pt-Maximalt iltoptag; vol.hast.(proc.) = ? L/min"	
* #MCS88158	"Kondital;Pt"	"Pt-Kondital; vol.hast.(proc.) = ? mL/kg/min"	
* #MCS88159	"Iltbehandling i hjemmet;Pt"	"Pt-Iltbehandling i hjemmet; arb.k.(0 1) = ?"	
* #MCS88160	"Livskvalitetsindex;Pt(psoriasis)"	"Pt(psoriasis)-Livskvalitetsindex (DLQI); antal(værdi 0-30) = ?"	
* #MCS88161	"Symptomscore;Pt(psoriasis)"	"Pt(psoriasis)-Symptomscore (PSSD); antal(værdi 0-100) = ?"	
* #MCS88162	"Sygdomsscore;Pt(psoriasis)"	"Pt(psoriasis)-Sygdomstegnscore (PSSD); antal(værdi 0-100) = ?"	
* #MCS88163	"Hudpåvirkning;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning (BSA); antal(værdi 0-100) = ?"	
* #MCS88164	"Hudpåvirkning intim;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning intimområde (BSA);  arb.k.(0 1) = ?"	
* #MCS88165	"Psoriasisgigtscore;Pt(psoriasis)"	"Pt(psoriasis)-Screening for psoriasisgigt (PEST); antal(værdi 0-5) = ?"	
* #MCS88166	"Hjerte/kar-helbred;Pt(psoriasis)"	"Pt(psoriasis)-Hjerte/kar helbredsmonitorering;  arb.k.(0 1) = ?"	
* #MCS88167	"Bivirkninger;Pt(psoriasis)"	"Pt(psoriasis)-Bivirkninger til behandling; arb.k.(0 1) = ?"	
* #MCS88168	"Helbredspåvirkning;Pt(psoriasis)"	"Pt(psoriasis)-Samlet helbredspåvirkning i seneste uge (PGA); antal(værdi 0-10) = ?"	
* #MCS88169	"Generel trivsel;Pt(psoriasis)"	"Pt(psoriasis)-Generel trivsel i seneste 2 uger (MDI); antal(værdi 0-5) = ?"	
* #MCS88170	"Behov-reumatolog;Pt(psoriasis)"	"Pt(psoriasis)-Behov for stillingtagning til reumatolog; arb.k.(0 1) = ?"	
* #MCS88171	"TTI (12mdr);Pt(AFLI)"	"Pt(AFLI)-Tid i Terapeutisk Index over 12 mdr. (TTI); ratio = ?"	
* #MCS88172	"PAID-5;Pt"	"Pt-Problem Areas in Diabetes (PAID-5); antal(værdi 0-20) = ?"	
* #MCS88173	"WHO-5;Pt"	"Pt-Trivselsindekset (WHO-5); antal(værdi 0-100) = ? "	
* #MCS88174	"Ryger du;Pt"	"Pt(rygning)-Ryger du; arb.akt.(ja;nej) = ?"	
* #MCS88175	"Øjne undersøgt ifm. diabetes;Pt"	"Pt(diabetes)-Øjne undersøgt for diabetesforandringer indenfor de seneste 2 år; arb.akt.(ja;nej;ej besvaret) = ?"	
* #MCS88176	"Fødder undersøgt hos fodterapeut;Pt"	"Pt(diabetes)-Fødder undersøgt hos fodterapeut indenfor det seneste år; arb.akt.(ja;nej;ej besvaret) = ?"	
* #MCS88177	"Hudpåvirkning Hoved;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning Hoved; arb.k.(0 1) = ?"	
* #MCS88178	"Hudpåvirkn. Overkrop;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning Overkrop; arb.k.(0 1) = ?"	
* #MCS88179	"Hudpåvirkning Arme;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning Arme; arb.k.(0 1) = ?"	
* #MCS88180	"Hudpåvirkning Ben;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning Ben; arb.k.(0 1) = ?"	
* #MCS88181	"Samtale;Pt(psoriasis)"	"Pt(psoriasis)-Emner til samtale; arb.k.(0 1) = ?"	
* #MCS88182	"Hudpåvirkning Ingen;Pt(psoriasis)"	"Pt(psoriasis)-Hudpåvirkning Ingen; arb.k.(0 1) = ?"	
* #MCS88183	"SCORE2 Hjerte;Pt"	"Pt-SCORE2 Hjerte (køn,alder,systolisk blodtryk,LDL-kolesterol,rygestatus); ratio=?"	
* #MCS88184	"FEV1% - efter reversibilitet;Lunge"	"Lunge-FEV1 i % af forventede værdi ( ift. højde, alder og køn) - efter reversibilitet; ratio = ?"	
* #MCS88185	"LDL-Kolesterol, beregn.anbef.mål;P"	"P(FLP mål)-LDL kolesterol beregnet anbefalet mål for kommende år; stofk. = ? mmol/L"	
* #MCS88186	"HbA1c, beregnet anbefalet mål;Hb(B)"	"Hb(B)(FLP mål)-HbA1c beregnet anbefalet mål for kommende år; stofratio = ?"	
* #MCS88187	"BT(sys), beregnet anbefalet mål;Arm"	"Arm(FLP mål)-Blodtryk(systolisk) beregnet anbefalet mål for kommende år = ? mmHg"	
* #MCS88188	"BT(dia), beregnet anbefalet mål;Arm"	"Arm(FLP mål)-Blodtryk(diastolisk) beregnet anbefalet mål for kommende år = ? mmHg"	
* #MCS88189	"TTI (3mdr);Pt(AFLI)"	"Pt(AFLI)-Tid i Terapeutisk Index over 3 mdr. (TTI); ratio = ?"	
* #MCS88190	"TTI (6mdr);Pt(AFLI)"	"Pt(AFLI)-Tid i Terapeutisk Index over 6 mdr. (TTI); ratio = ?"	
* #MCS88191	"TTI (total interval);Pt(AFLI)"	"Pt(AFLI)-Tid i Terapeutisk Index total interval (TTI); ratio = ?"	
* #MCS88192	"Skridt per dag;Pt"	"Pt-Skridt; antal per dag (værdi) = ?"	
* #MCS88193	"Skridt per uge;Pt"	"Pt-Skridt; antal per uge (værdi) = ?"	
* #MCS88194	"Skridt;Pt"	"Pt-Skridt; antal (værdi) = ?"	
* #MCS88195	"PROMIS-10 Fysisk helbred;Pt"	"Pt-Generelt fysisk helbreds score (PROMIS-10); antal(værdi 16.2-67.7) = ?"	
* #MCS88196	"PROMIS-10 Mentalt helbred;Pt"	"Pt-Generelt mentalt helbreds score (PROMIS-10); antal(værdi 21.2-67.6) = ?"	
* #MCS88197	"SCORE2 Diabetes;Pt"	"Pt-SCORE2 Diabetes (køn,alder,debutår,systolisk blodtryk,total- og HDL-kolesterol,rygestatus,eGFR,HbA1c); ratio=?"	
* #MCS88198	"BASIC SCORE (demens);Pt"	"Pt-BASIC (Brief Assessment of Impaired Cognition SCORE, Demens); antal(værdi 0-25) = ?"	
* #MCS90001	""	"øjenscreenings-indikation (0-5);øjenscreenings-indikation"	
* #MCS90002	"Tidligere kataraktop.;højre øje"	"Tidligere kataraktoperation;højre øje"	
* #MCS90003	"Tidligere kataraktop.; venstre øje"	"Tidligere kataraktoperation; venstre øje"	
* #MCS90004	"Tidl vitreoretinal kirg;højre øje"	"Tidligere vitreoretinal kirurgi for diabeteskomplikation;højre øje"	
* #MCS90005	"Tidl vitreoretinal kirg;venstre øje"	"Tidligere vitreoretinal kirurgi for diabeteskomplikation;venstre øje"	
* #MCS90006	"Synsstyrke;højre øje"	"Synsstyrke;højre øje"	
* #MCS90007	"Synsstyrke;venstre øje"	"Synsstyrke;venstre øje"	
* #MCS90010	"Retinastatus;højre øje"	"Retinastatus;højre øje ((0-7)(51-55))"	
* #MCS90011	"Retinastatus;venstre øje"	"Retinastatus;venstre øje ((0-7)(51-55))"	
* #MCS90012	"Maculopati-status;højre øje"	"Maculopati-status;højre øje (0-7)"	
* #MCS90013	"Maculopati-status;venstre øje"	"Maculopati-status;venstre øje (0-7)"	
* #MCS90014	""	"Indikation for næste øjenlægekontakt (0-6);Indikation f næste øjenlægekontakt"	
* #MCS90015	""	"Tidspunkt for næste Screening ;Tidspunkt for næste Screening"	
* #MCS90016	"Slårede medier-Katarakt;højre øje"	"Slårede medier-Katarakt;højre øje"	
* #MCS90017	"Slårede medier-Katarakt;venstre øje"	"Slårede medier-Katarakt;venstre øje"	
* #MCS90018	"Slår med.-Glaslegemebl;højre øje"	"Slårede medier-Glaslegemeblødning;højre øje"	
* #MCS90019	"Slår med.-Glaslegemebl;venstre øje"	"Slårede medier-Glaslegemeblødning;venstre øje"	
* #MCS90020	"Slår med.-An/ukendt årsag;h� øje"	"Slårede medier-Anden / ukendt årsag;højre øje"	
* #MCS90021	"Slår med.-An/ukendt årsag;ven øje"	"Slårede medier-Anden / ukendt årsag;venstre øje"	
